#!/bin/bash

echo -n "Number of Genes (l): "
read l
echo -n "Population size (n): "
read n
echo -n "Generations (G): "
read G
echo -n "Probability of Mutation (pm): "
read pm
echo -n "Probability of Crossover (pc): "
read pc
echo -n "Name of Experiment: "
read name
echo -n "Number of runs: "
read run_size

mkdir $name
dirname=${name}"/"

for i in $(seq 1 $run_size)
do
	f="run"${i}
	filename=${f}".csv"

	loc=${dirname}${filename}
	echo $loc
	echo "Avg Gen Fitness, Highest Gen Fitness, Avg # of Correct Bits," > $loc

	./proj5 $l $n $G $pm $pc >> $loc
	echo $'\n' >> $loc

	cat $loc >> ${dirname}"master.csv"
done